version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t libs

  build:
    commands:
      - echo "Creating deployment package..."
      - cd libs
      - zip -r ../deployment_package.zip .  # Archive all contents of 'libs'
      - cd ..
      - zip -g deployment_package.zip lambda_function.py  # Add lambda_function.py

  post_build:
    commands:
      - echo "Uploading deployment package to S3..."
      - aws s3 cp deployment_package.zip s3://cicd-bucketss/
      - echo "Updating Lambda function..."
      - aws lambda update-function-code --function-name github-to-lamda-cide --s3-bucket cicd-bucketss --s3-key deployment_package.zip
      - echo "Deployment complete!"

artifacts:
  files:
    - deployment_package.zip
