version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t libs
      - echo "Verifying zip installation..."
      - which zip  # Verify zip is installed
      - if ! which zip; then echo "zip installation failed!"; exit 1; fi  # Fail if zip is not found

  build:
    commands:
      - echo "Creating deployment package with zip..."
      - cd libs
      - zip -r ../deployment_package.zip *  # Archive all contents of 'libs' using zip
      - cd ..
      - zip deployment_package.zip lambda_function.py  # Add 'lambda_function.py' to the archive

  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp deployment_package.zip s3://cicd-bucketss/
      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name github-to-lambda-cide --s3-bucket cicd-bucketss --s3-key deployment_package.zip
      - echo "Deployment complete!"

artifacts:
  files:
    - deployment_package.zip
