version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t libs
      - echo "Installing 7-Zip..."
      - yum install -y p7zip  # Use 'yum' for Amazon Linux
  build:
    commands:
      - echo "Creating deployment package with 7z..."
      - cd lib
      - 7z a ../deployment_package.7z *  # Archive all contents of 'lib'
      - cd ..
      - 7z a deployment_package.7z lambda_function.py  # Add 'lambda_function.py' to the archive
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp deployment_package.7z s3://cicd-bucketss/
      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name github-to-lambda-cicd --s3-bucket cicd-bucketss --s3-key deployment_package.7z
      - echo "Deployment complete!"
